<?php

namespace Hacco\DeeeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * devisMaterielsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class devisMaterielsRepository extends EntityRepository
{
}
